version: "2"
services:
  smart-agent:
    container_name: smart-agent
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "8080:3000"
